# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'LoginApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    # pod 'FacebookLogin'
    # pod 'SwiftKeychainWrapper'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'

  # Pods for LoginApp

  target 'LoginAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
